# Generated by Django 5.2.12 on 2026-05-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
