# Generated by Django 5.2.12 on 2026-03-23 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_remove_enrollment_resource'),
        ('resources', '0002_course_delete_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='Course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.course'),
        ),
    ]
