# Generated by Django 5.2.12 on 2026-03-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0003_enrollment_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='enrolled_at',
            new_name='enrolled_on',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='status',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
