# Generated by Django 5.2.12 on 2026-04-07 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_title',
            new_name='title',
        ),
    ]
